### PR TITLE
Destroy toplevel handles on application switcher destruction

### LINKED ISSUE #4488: ASan detects heap use after free when miral-app's tiling window manager is used
### Version

main

### Environment

Mir under ASan.

### What happened? What did you expect to happen?

When running `miral-app --window-manager=tiling` on an ASan build, Mir crashes immediately with a heap use after free error.

### Reproduction steps

_No response_

### Relevant log output

```shell
==482738==ERROR: AddressSanitizer: heap-use-after-free on address 0x7411479cddd0 at pc 0x77a14afa6b56 bp 0x73a11048c050 sp 0x73a11048c048
READ of size 8 at 0x7411479cddd0 thread T28
    #0 0x77a14afa6b55 in auto (anonymous namespace)::WaylandApp::remove(zwlr_foreign_toplevel_handle_v1*)::'lambda'(auto const&)::operator()<(anonymous namespace)::ToplevelInfo>(auto const&) 
const /home/tarek/code-projects/mir/src/miral/application_switcher.cpp:379:28
    #1 0x77a14afa6b0c in auto std::__invoke_impl<bool, (anonymous namespace)::WaylandApp::remove(zwlr_foreign_toplevel_handle_v1*)::'lambda'(auto const&)&, (anonymous namespace)::ToplevelInfo
&>(std::__invoke_other, (anonymous namespace)::WaylandApp::remove(zwlr_foreign_toplevel_handle_v1*)::'lambda'(auto const&)&, (anonymous namespace)::ToplevelInfo&) /usr/lib/gcc/x86_64-linux-gn
u/15/../../../../include/c++/15/bits/invoke.h:63:14
    #2 0x77a14afa6adc in std::__invoke_result<auto, (anonymous namespace)::ToplevelInfo&>::type std::__invoke<(anonymous namespace)::WaylandApp::remove(zwlr_foreign_toplevel_handle_v1*)::'lam
bda'(auto const&)&, (anonymous namespace)::ToplevelInfo&>(auto&&, (anonymous namespace)::ToplevelInfo&) /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/invoke.h:98:14
    #3 0x77a14afa69be in T std::ranges::__find_if_fn::operator()<__gnu_cxx::__normal_iterator<(anonymous namespace)::ToplevelInfo*, std::vector<(anonymous namespace)::ToplevelInfo, std::alloc
ator<(anonymous namespace)::ToplevelInfo>>>, __gnu_cxx::__normal_iterator<(anonymous namespace)::ToplevelInfo*, std::vector<(anonymous namespace)::ToplevelInfo, std::allocator<(anonymous name
space)::ToplevelInfo>>>, std::identity, (anonymous namespace)::WaylandApp::remove(zwlr_foreign_toplevel_handle_v1*)::'lambda'(T const&)>(T, __gnu_cxx::__normal_iterator<(anonymous namespace):
:ToplevelInfo*, std::vector<(anonymous namespace)::ToplevelInfo, std::allocator<(anonymous namespace)::ToplevelInfo>>>, (anonymous namespace)::WaylandApp::remove(zwlr_foreign_toplevel_handle_
v1*)::'lambda'(T const&), T1) const /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/ranges_util.h:560:16
    #4 0x77a14afa677a in std::__conditional<borrowed_range<T>>::type<decltype(ranges::__access::__begin(std::declval<T&>())), std::ranges::dangling> std::ranges::__find_if_fn::operator()<std:
:vector<(anonymous namespace)::ToplevelInfo, std::allocator<(anonymous namespace)::ToplevelInfo>>&, std::identity, (anonymous namespace)::WaylandApp::remove(zwlr_foreign_toplevel_handle_v1*):
:'lambda'(T const&)>(T&&, (anonymous namespace)::WaylandApp::remove(zwlr_foreign_toplevel_handle_v1*)::'lambda'(T const&), T0) const /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/1
5/bits/ranges_util.h:571:9
    #5 0x77a14afa62c2 in (anonymous namespace)::WaylandApp::remove(zwlr_foreign_toplevel_handle_v1*) /home/tarek/code-projects/mir/src/miral/application_switcher.cpp:377:25
    #6 0x77a14af9d264 in (anonymous namespace)::WaylandApp::handle_closed(void*, zwlr_foreign_toplevel_handle_v1*) /home/tarek/code-projects/mir/src/miral/application_switcher.cpp:586:15
    #7 0x77a14aab7ed5  (/lib/x86_64-linux-gnu/libffi.so.8+0x7ed5) (BuildId: 3e85793bc345fcdd4dc0aaa1375df2da4e2cabf5)
    #8 0x77a14aab4ba5  (/lib/x86_64-linux-gnu/libffi.so.8+0x4ba5) (BuildId: 3e85793bc345fcdd4dc0aaa1375df2da4e2cabf5)
    #9 0x77a14aab74ad in ffi_call (/lib/x86_64-linux-gnu/libffi.so.8+0x74ad) (BuildId: 3e85793bc345fcdd4dc0aaa1375df2da4e2cabf5)
    #10 0x77a14b3dd98a  (/lib/x86_64-linux-gnu/libwayland-client.so.0+0x798a) (BuildId: 19d00f73bc917f4c9ba26b647b1acda7a5e45488)
    #11 0x77a14b3de7c8  (/lib/x86_64-linux-gnu/libwayland-client.so.0+0x87c8) (BuildId: 19d00f73bc917f4c9ba26b647b1acda7a5e45488)
    #12 0x77a14b3debc2 in wl_display_dispatch_queue_pending (/lib/x86_64-linux-gnu/libwayland-client.so.0+0x8bc2) (BuildId: 19d00f73bc917f4c9ba26b647b1acda7a5e45488)
    #13 0x77a14b3e2339 in wl_display_dispatch_queue_timeout (/lib/x86_64-linux-gnu/libwayland-client.so.0+0xc339) (BuildId: 19d00f73bc917f4c9ba26b647b1acda7a5e45488)
    #14 0x77a14b3e240e in wl_display_dispatch_queue (/lib/x86_64-linux-gnu/libwayland-client.so.0+0xc40e) (BuildId: 19d00f73bc917f4c9ba26b647b1acda7a5e45488)
    #15 0x77a14b3e24ea in wl_display_roundtrip_queue (/lib/x86_64-linux-gnu/libwayland-client.so.0+0xc4ea) (BuildId: 19d00f73bc917f4c9ba26b647b1acda7a5e45488)
    #16 0x77a14afb79bd in std::unique_ptr<wl_display, int (*)(wl_display*)>::~unique_ptr() /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/unique_ptr.h:398:4
    #17 0x77a14afb7aaf in miral::tk::WaylandApp::~WaylandApp() /home/tarek/code-projects/mir/src/miral/wayland_app.h:71:35
    #18 0x77a14af9d870 in (anonymous namespace)::WaylandApp::~WaylandApp() /home/tarek/code-projects/mir/src/miral/application_switcher.cpp:295:7
    #19 0x77a14afa7424 in void std::destroy_at<(anonymous namespace)::WaylandApp>((anonymous namespace)::WaylandApp*) /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/stl_cons
truct.h:88:15
    #20 0x77a14afa73c4 in void std::_Destroy<(anonymous namespace)::WaylandApp>((anonymous namespace)::WaylandApp*) /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/stl_constr
uct.h:164:7
    #21 0x77a14af9ca2e in void std::allocator_traits<std::allocator<void>>::destroy<(anonymous namespace)::WaylandApp>(std::allocator<void>&, (anonymous namespace)::WaylandApp*) /usr/lib/gcc/
x86_64-linux-gnu/15/../../../../include/c++/15/bits/alloc_traits.h:819:4
    #22 0x77a14af9ca2e in std::_Sp_counted_ptr_inplace<(anonymous namespace)::WaylandApp, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/lib/gcc/x86_64-linux-gnu/15/../.
./../../include/c++/15/bits/shared_ptr_base.h:615:2
    #23 0x77a14af9ad24 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/shared_ptr_base.h:345:8
    #24 0x77a14af9ab89 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/shared_ptr_base.h:1069:11
    #25 0x77a14afa76e8 in std::__shared_ptr<(anonymous namespace)::WaylandApp, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/sh
ared_ptr_base.h:1531:31
    #26 0x77a14afa7578 in std::__shared_ptr<(anonymous namespace)::WaylandApp, (__gnu_cxx::_Lock_policy)2>::operator=(std::__shared_ptr<(anonymous namespace)::WaylandApp, (__gnu_cxx::_Lock_po
licy)2>&&) /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/shared_ptr_base.h:1627:2
    #27 0x77a14af9b9d0 in std::shared_ptr<(anonymous namespace)::WaylandApp>::operator=(std::shared_ptr<(anonymous namespace)::WaylandApp>&&) /usr/lib/gcc/x86_64-linux-gnu/15/../../../../incl
ude/c++/15/bits/shared_ptr.h:439:27
    #28 0x77a14afb2970 in miral::ApplicationSwitcher::Self::run_client(wl_display*) /home/tarek/code-projects/mir/src/miral/application_switcher.cpp:734:13
    #29 0x77a14af9b354 in miral::ApplicationSwitcher::operator()(wl_display*) /home/tarek/code-projects/mir/src/miral/application_switcher.cpp:807:11
    #30 0x77a14afc73d5 in void std::__invoke_impl<void, miral::ApplicationSwitcher&, wl_display*>(std::__invoke_other, miral::ApplicationSwitcher&, wl_display*&&) /usr/lib/gcc/x86_64-linux-gn
u/15/../../../../include/c++/15/bits/invoke.h:63:14
    #31 0x77a14afc733c in std::enable_if<is_invocable_r_v<void, miral::ApplicationSwitcher&, wl_display*>, void>::type std::__invoke_r<void, miral::ApplicationSwitcher&, wl_display*>(miral::A
pplicationSwitcher&, wl_display*&&) /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/invoke.h:113:2
    #32 0x77a14afc7194 in std::_Function_handler<void (wl_display*), miral::ApplicationSwitcher>::_M_invoke(std::_Any_data const&, wl_display*&&) /usr/lib/gcc/x86_64-linux-gnu/15/../../../../
include/c++/15/bits/std_function.h:292:9
    #33 0x77a14b0f81e6 in std::function<void (wl_display*)>::operator()(wl_display*) const /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/std_function.h:593:9
    #34 0x77a14b0f7d8a in WlInternalClientRunner<miral::StartupInternalClient::Self>::run(mir::Server&)::'lambda'()::operator()() const /home/tarek/code-projects/mir/src/miral/internal_client
.cpp:132:21
    #35 0x77a14b0f7b74 in void std::__invoke_impl<void, WlInternalClientRunner<miral::StartupInternalClient::Self>::run(mir::Server&)::'lambda'()>(std::__invoke_other, WlInternalClientRunner<
miral::StartupInternalClient::Self>::run(mir::Server&)::'lambda'()&&) /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/invoke.h:63:14
    #36 0x77a14b0f7b34 in std::__invoke_result<WlInternalClientRunner<miral::StartupInternalClient::Self>::run(mir::Server&)::'lambda'()>::type std::__invoke<WlInternalClientRunner<miral::Sta
rtupInternalClient::Self>::run(mir::Server&)::'lambda'()>(WlInternalClientRunner<miral::StartupInternalClient::Self>::run(mir::Server&)::'lambda'()&&) /usr/lib/gcc/x86_64-linux-gnu/15/../../.
./../include/c++/15/bits/invoke.h:98:14
    #37 0x77a14b0f7b0c in void std::thread::_Invoker<std::tuple<WlInternalClientRunner<miral::StartupInternalClient::Self>::run(mir::Server&)::'lambda'()>>::_M_invoke<0ul>(std::_Index_tuple<0
ul>) /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/std_thread.h:303:13
    #38 0x77a14b0f7ae4 in std::thread::_Invoker<std::tuple<WlInternalClientRunner<miral::StartupInternalClient::Self>::run(mir::Server&)::'lambda'()>>::operator()() /usr/lib/gcc/x86_64-linux-
gnu/15/../../../../include/c++/15/bits/std_thread.h:310:11
    #39 0x77a14b0f7a28 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<WlInternalClientRunner<miral::StartupInternalClient::Self>::run(mir::Server&)::'lambda'()>>>::_M_run() /usr
/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/std_thread.h:255:13
    #40 0x77a14a8f2583  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xf2583) (BuildId: 280f658f43aae7a7f92bba6ec4c5d96bc2b53a7a)
    #41 0x5d9677edd75a in asan_thread_start(void*) crtstuff.c
    #42 0x77a14a4a3d63 in start_thread nptl/pthread_create.c:448:8
    #43 0x77a14a5373bb in __GI___clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

!!! Fatal signal received. Attempting cleanup, but deadlock may occur
{"datetime": "2025-12-03T08:01:58Z", "appid": "miral-shell.bin", "event": "crash", "description": "Fatal signal received"}
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
```

### PR DESCRIPTION
**Pull request by tarek-y-ismail**
Closes #4488 

## What's new?

Fixes a bug where the application switcher would be destroyed without destroying the toplevel handles, then the unique_ptr of the display would initiate a roundtrip. The server would then send `closed` onto each handle (which again, we forgot to destroy so we still receive events from). This would then try to access data from the now-freed `WaylandApp`, triggering ASan.

It's still unknown to me why this only happens with the tiling window manager.

## How to test

1. Revert the commit in this PR
2. Build Mir with `-DCMAKE_BUILD_TYPE=AddressSanitizer`
3. Run `miral-app --window-manager=tiling`
4. Exit Mir
5. Observe ASan screaming at you about a heap use after free
6. Un-revert the commit in this PR
7. Steps 2,3,4 again...
8. Observe as ASan stops mentioning the heap use after free

### CODE REVIEW

File: src/miral/application_switcher.cpp [hunk 1]
```diff
@@ -584,6 +596,7 @@ class WaylandApp : public miral::tk::WaylandApp
     {
         auto const self = static_cast<WaylandApp*>(data);
         self->remove(handle);
+        zwlr_foreign_toplevel_handle_v1_destroy(handle);
```
Comment (AlanGriffiths) [inline src/miral/application_switcher.cpp]: I would expect this in `remove()` not in the thunk.

But I guess it is pre-existing to spread logic around like this - see `handle_state()` for another example.

**Review by mattkae — APPROVED** [review]
Whoopsie! Nice catch 😄
