### PR TITLE
fix: free xcb_reply's with scoped smart pointers

### LINKED ISSUE #4559: XCB replies not always freed
Specifically, the return values from `xcb_randr_query_version_reply`, `xcb_randr_get_screen_info_reply`. Though others may also be leaking. These replies should be freed at the end of their current scope.

### PR DESCRIPTION
**Pull request by aliihsancengiz**
Closes #4559

Related: #4559

## What's new?

Previously, some of xcb_*_reply results were never freed; this PR uses a scope-based smart pointer to free results when they get out of scope.

## Checklist

- [ ] Tests added and pass
- [ ] Adequate documentation added
- [ ] (optional) Added Screenshots or videos

### CODE REVIEW

File: src/platforms/x11/graphics/egl_helper.cpp [hunk 1]
```diff
@@ -176,10 +177,9 @@ namespace
 auto size_for_x_win(xcb_connection_t* xcb_conn, xcb_window_t win) -> mir::geometry::Size
 {
     auto cookie = xcb_get_geometry(xcb_conn, win);
-    if (auto reply = xcb_get_geometry_reply(xcb_conn, cookie, nullptr))
+    if (auto const reply = mir::make_unique_cptr(xcb_get_geometry_reply(xcb_conn, cookie, nullptr)); reply)
```
Comment (AlanGriffiths) [inline src/platforms/x11/graphics/egl_helper.cpp]: Can be simpler:

```suggestion
    if (auto const reply = mir::make_unique_cptr(xcb_get_geometry_reply(xcb_conn, cookie, nullptr)))
```

File: src/platforms/x11/graphics/egl_helper.cpp [hunk 2]
```diff
@@ -15,6 +15,7 @@
  */
 
 #include "egl_helper.h"
+#include "mir/c_memory.h"
```
Comment (tarek-y-ismail) [inline src/platforms/x11/graphics/egl_helper.cpp]:
```suggestion
#include <mir/c_memory.h>
```

Should be moved to the include group below  it.

File: src/platforms/x11/graphics/egl_helper.cpp (hunk 1 above)
Comment (aliihsancengiz) [reply src/platforms/x11/graphics/egl_helper.cpp]: Thanks for the hint, addressed and applied for other use case of xcb_* functions you listed.

File: src/server/frontend_xwayland/xwayland_cursors.cpp [hunk 3]
```diff
@@ -18,6 +18,7 @@
  *
  */
 
+#include "mir/c_memory.h"
 #include "xcb_connection.h"
 #include "xwayland_cursors.h"
 #include "xwayland_log.h"
```
Comment (AlanGriffiths) [inline src/server/frontend_xwayland/xwayland_cursors.cpp]:
```suggestion
#include "xwayland_cursors.h"
#include "xcb_connection.h"
#include "xwayland_log.h"

#include <mir/c_memory.h>
```

File: src/platforms/x11/graphics/egl_helper.cpp [hunk 4]
```diff
@@ -15,6 +15,7 @@
...
```
Comment (AlanGriffiths) [inline src/platforms/x11/graphics/egl_helper.cpp]:
```suggestion

#include <mir/c_memory.h>
```

**Review by AlanGriffiths — CHANGES_REQUESTED** [review]
Just some include tweaking:

1. the first header should be the interface offered by the .cpp file
2. then local headers (typically those in the current directory)
3. then mir headers
...

**Comment by aliihsancengiz** [comment]
> Just some include tweaking:
> 
> 1. the first header should be the interface offered by the .cpp file
> 2. then local headers (typically those in the current directory)
> 3. then mir headers
>    ...

Thanks @AlanGriffiths , looks like my LSP is putting those out of order.

Addressed comments and rebased with main now.

File: src/platforms/x11/x11_resources.cpp [hunk 5]
```diff
@@ -97,19 +98,18 @@ class BasicXCBConnection : public mx::XCBConnection
...
-        free(reply);
         return atom;
     }
 
     auto get_output_refresh_rate() const -> double override
     {
         // I'm assuming we handle xcb errors somewhere with events.
         auto ver_cookie = xcb_randr_query_version_unchecked(conn, 1, 2);
-        xcb_randr_query_version_reply(conn, ver_cookie,nullptr);
+        auto const version_reply = mir::make_unique_cptr(xcb_randr_query_version_reply(conn, ver_cookie,nullptr));
```
[the remark this answers is not in the document]
Comment (AlanGriffiths) [reply src/platforms/x11/x11_resources.cpp]:
```suggestion
        free(xcb_randr_query_version_reply(conn, ver_cookie, nullptr));
```

File: src/platforms/x11/x11_resources.cpp [hunk 6]
```diff
@@ -97,19 +98,18 @@ class BasicXCBConnection : public mx::XCBConnection
...
         auto screen_cookie = xcb_randr_get_screen_info_unchecked(conn,screen_->root);
-        auto screen_reply = xcb_randr_get_screen_info_reply(conn, screen_cookie, nullptr);
+        auto const screen_reply = mir::make_unique_cptr(xcb_randr_get_screen_info_reply(conn, screen_cookie, nullptr));
         auto refresh_rate = static_cast<double>(screen_reply->rate);
         mir::log_debug("Detected %.2fHz host output refresh rate.", refresh_rate);
         return screen_reply->rate;
```
[the remark this answers is not in the document]
Comment (AlanGriffiths) [reply src/platforms/x11/x11_resources.cpp:115]: > Missing null check before dereferencing screen_reply

_If_ there is a problem, then it is pre-existing: doesn't block this PR
