### PR TITLE
Fix/logging snprintf negative time 4556

### LINKED ISSUE #4556: Fix logging `snprintf` with negative time values
https://github.com/canonical/mir/blob/a3798aab082e6cc483538ba274cdf10d9c79384f/src/common/logging/input_timestamp.cpp#L30-L31

The reminder operator preserves the sign `age_ns` is negative (saw it a couple of times when debugging), so the output can looks something like `-1.-500000ms`

### PR DESCRIPTION
**Pull request by DigraJatin**
Closes #4556 

## What's new?

1. Updated input_timestamp() to correctly handle future timestamps.
2. Replaced the buggy modulo logic—which produced confusing "double negative" strings like -100.-500ms ago—with absolute duration calculations.
3. Added a contextual suffix (ago vs in future) to make the logs human-readable regardless of clock drift or event timing. (No negative sign would be printed for future timestamps).

Past values will be printed like - 
`500 ms ago`
Future values will be printed like - 
`100 ms in future`

## How to test
Added unit tests for the function, run `./bin/mir_unit_tests --gtest_filter=TimestampTest.*` and verify.

## Checklist

- [ ✅] Tests added and pass
- [ ✅] Adequate documentation added

### CODE REVIEW

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+#include <mir/logging/input_timestamp.h>
+
+#include <gtest/gtest.h>
+#include <chrono>
+#include <string>
+#include <cstdio>
```
Comment (tarek-y-ismail) [inline tests/unit-tests/logging/test_input_timestamp.cpp]: Why are we including this?

**Review by tarek-y-ismail — CHANGES_REQUESTED** [review]
Looks good. One small nit...

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+
+using namespace std::chrono;
+namespace ml = mir::logging;
+
+class TimestampTest : public ::testing::Test {
+};
```
Comment (AlanGriffiths) [inline tests/unit-tests/logging/test_input_timestamp.cpp]: You don't need a test fixture - so don't declare one: Just use the `TEST` macro instead of the `TEST_F` macro.

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+
+TEST_F(TimestampTest, HandlesPastTime) {
```
Comment (AlanGriffiths) [inline tests/unit-tests/logging/test_input_timestamp.cpp]: 1. We usually put braces on the next line
2. You don't need a test fixture
3. we use snake_case for test names
 
```suggestion
TEST(TimestampTest, past_time_is_correctly_formatted) 
{
```

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+    auto now = steady_clock::now().time_since_epoch();
+    nanoseconds past_event = duration_cast<nanoseconds>(now - milliseconds(500));
+
+    std::string out = ml::input_timestamp(past_event);
+
+    EXPECT_EQ(out.find(".-"), std::string::npos);
+    EXPECT_NE(out.find("500.000000ms ago"), std::string::npos);
```
Comment (AlanGriffiths) [inline tests/unit-tests/logging/test_input_timestamp.cpp]: Non-blocking, but we prefer the "fluent" style of test expectations:

```suggestion
    EXPECT_THAT(out, Not(HasSubstr(".-"));
    EXPECT_THAT(out, HasSubstr("500.000000ms ago"));
```

Note this needs a bit more context from gmock before it compiles:

```c++
#include <gmock/gmock.h>
...
using namespace testing;
```

File: src/common/logging/input_timestamp.cpp [hunk 5]
```diff
@@ -26,9 +26,15 @@ std::string mir::logging::input_timestamp(nanoseconds when)
...
+    long long const milliseconds = abs_age_ns / 1000000LL;
+    long long const sub_milliseconds = abs_age_ns % 1000000LL;
+    
+    char const* sign_suffix = (age_ns < 0) ? "in future" : "ago";
+
     char str[64];
-    snprintf(str, sizeof str, "%lld (%lld.%06lldms ago)",
-             when_ns, age_ns / 1000000LL, age_ns % 1000000LL);
+    snprintf(str, sizeof str, "%lld (%lld.%06lldms %s)",
+             when_ns, milliseconds, sub_milliseconds, sign_suffix);
```
Comment (AlanGriffiths) [inline src/common/logging/input_timestamp.cpp]: Non blocking (pre-existing) the `str` buffer can be replaced by `std::format`

File: src/common/logging/input_timestamp.cpp [hunk 6]
```diff
@@ -26,9 +26,15 @@ std::string mir::logging::input_timestamp(nanoseconds when)
     long long const now_ns = duration_cast<nanoseconds>(now).count();
     long long const age_ns = now_ns - when_ns;
 
+    long long const abs_age_ns = std::llabs(age_ns);
```
Comment (AlanGriffiths) [inline src/common/logging/input_timestamp.cpp:30]: We should be including `cstdlib` for `llabs()`

**Review by AlanGriffiths — CHANGES_REQUESTED** [review]
Some tweaks and some non-blocking comments you can chose to ignore

File: src/common/logging/input_timestamp.cpp (hunk 5 above)
Comment (DigraJatin) [reply src/common/logging/input_timestamp.cpp]: Leaving this for now, i think better would be to have a enhacement/refactor ticket to remove such buffers throughout codebase.

File: tests/unit-tests/logging/test_input_timestamp.cpp (hunk 1 above)
Comment (DigraJatin) [reply tests/unit-tests/logging/test_input_timestamp.cpp]: removed.

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+ */
+
+#include <mir/logging/input_timestamp.h>
+
+#include <gtest/gtest.h>
+#include <gmock/gmock.h>
+#include <chrono>
+#include <string>
+
+using namespace std::chrono;
```
Comment (tarek-y-ismail) [inline tests/unit-tests/logging/test_input_timestamp.cpp:24]: You can additionally use `std::chrono_literals` which will enable you to define `past_event` as 
```
    auto const past_event = steady_clock::now().time_since_epoch() - 500ms;
```
The same applies to `future_event`.

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 8]
```diff
@@ -0,0 +1,50 @@
...
+using namespace testing;
+namespace ml = mir::logging;
+
+TEST(TimestampTest, past_time_is_correctly_formatted)
+{
+    auto now = steady_clock::now().time_since_epoch();
+    nanoseconds past_event = duration_cast<nanoseconds>(now - milliseconds(500));
```
Comment (tarek-y-ismail) [inline tests/unit-tests/logging/test_input_timestamp.cpp]: These two lines can be merged as mentioned above. The final variable can also be const.

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+
+    std::string out = ml::input_timestamp(past_event);
+
+    EXPECT_THAT(out, Not(HasSubstr(".-")));
+    EXPECT_THAT(out, HasSubstr("500.000000ms ago"));
```
Comment (tarek-y-ismail) [inline tests/unit-tests/logging/test_input_timestamp.cpp]: Seems like CI has some float formatting inconsistencies. I think you should loosen the test a bit. Just testing for "500.0" and "ago" should be enough.

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 10]
```diff
@@ -0,0 +1,50 @@
...
+}
+
+TEST(TimestampTest, future_time_is_correctly_formatted)
+{
+    auto now = steady_clock::now().time_since_epoch();
+    nanoseconds future_event = duration_cast<nanoseconds>(now + nanoseconds(1000000123LL));
```
Comment (tarek-y-ismail) [inline tests/unit-tests/logging/test_input_timestamp.cpp]: Can be one line & const.

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 11]
```diff
@@ -0,0 +1,50 @@
...
+
+    std::string out = ml::input_timestamp(future_event);
+
+    EXPECT_THAT(out, Not(HasSubstr(".-")));
+    EXPECT_THAT(out, HasSubstr("in future"));
+    EXPECT_THAT(out, HasSubstr("1000.000123ms"));
```
Comment (tarek-y-ismail) [inline tests/unit-tests/logging/test_input_timestamp.cpp]: Again, CI has float formatting inconsistencies. Might have to bump the timestamp by a millisecond and check for "1000.0" and "in the future"

File: src/common/logging/input_timestamp.cpp [hunk 12]
```diff
@@ -26,9 +27,15 @@ std::string mir::logging::input_timestamp(nanoseconds when)
...
+    long long const milliseconds = abs_age_ns / 1000000LL;
+    long long const sub_milliseconds = abs_age_ns % 1000000LL;
+
+    char const* sign_suffix = (age_ns < 0) ? "in future" : "ago";
```
Comment (tarek-y-ismail) [inline src/common/logging/input_timestamp.cpp]:
```suggestion
    char const* sign_suffix = (age_ns < 0) ? "in the future" : "ago";
```

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 13]
```diff
@@ -0,0 +1,52 @@
...
+#include <chrono>
+#include <string>
+
+using namespace std::chrono;
+using namespace testing;
+namespace ml = mir::logging;
+
+TEST(TimestampTest, past_time_is_correctly_formatted)
+{
+    using namespace std::chrono_literals;
```
Comment (tarek-y-ismail) [inline tests/unit-tests/logging/test_input_timestamp.cpp]: Small nit: Since this isn't a header file, you can move this to the top of the file safely. Though it's not a big issue unless we add a lot more tests.

**Review by tarek-y-ismail — APPROVED** [review]
Looking good! Now let's see if CI is happy.

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 14]
```diff
@@ -0,0 +1,52 @@
...
+
+    EXPECT_THAT(out, Not(HasSubstr(".-")));
+    EXPECT_THAT(out, HasSubstr("500.0"));
+    EXPECT_THAT(out, HasSubstr("ms ago"));
+}
+
+TEST(TimestampTest, future_time_is_correctly_formatted)
+{
+    using namespace std::chrono_literals;
+    auto const future_event = steady_clock::now().time_since_epoch() + 1000ms + 123ns;
```
Comment (tarek-y-ismail) [inline tests/unit-tests/logging/test_input_timestamp.cpp]: Looks like CI still isn't happy. I tried

```suggestion
    auto const future_event = steady_clock::now().time_since_epoch() + 1000ms + 10us;
```

and it seems to work consistently locally. Can you try that?

**Review by tarek-y-ismail — CHANGES_REQUESTED** [review]

**Comment by DigraJatin** [comment]
Not sure what's failing now 😅

**Comment by Saviq** [comment]
> Not sure what's failing now 😅

Not your fault @DigraJatin:
- #4610

Thanks for this!
