### PR TITLE
Fix XWayland scaling attempt 2

### LINKED ISSUE #3508: Scaling of XWayland apps broken
It seems that we're a bit confused when `x11-scale=2.0`. Client *input* is scaled to the window border you see there, but the rendering is not :grin: 
Screenshot of the problem

### PR DESCRIPTION
**Pull request by tarek-y-ismail**
Fixes: #3554, #3508

### CODE REVIEW

File: src/server/frontend_xwayland/xwayland_surface.cpp [hunk 1]
```diff
@@ -1267,26 +1267,6 @@ void mf::XWaylandSurface::prep_surface_spec(ProofOfMutexLock const&, msh::Surfac
...
-            }
-        };
-
-    scale_size_clamped(mods.width);
-    scale_size_clamped(mods.height);
-    scale_size_clamped(mods.min_width);
-    scale_size_clamped(mods.min_height);
-    scale_size_clamped(mods.max_width);
-    scale_size_clamped(mods.max_height);
-
```
Comment (AlanGriffiths) [inline src/server/frontend_xwayland/xwayland_surface.cpp:1289]: We should not be dropping the clamping. (Rewriting using `std::clamp` could be a thing though)

**Review by AlanGriffiths — CHANGES_REQUESTED** [review]
Apart from dropping the clamp logic, this looks sensible

File: src/server/frontend_xwayland/xwayland_surface.cpp (hunk 1 above)
Comment (AlanGriffiths) [reply src/server/frontend_xwayland/xwayland_surface.cpp:1289]: That makes sense now.

**Review by AlanGriffiths — APPROVED** [review]
Looks sensible to me. Will leave @RAOF to have the final say

**Comment by RAOF** [comment]
Hm. This is a partial fix, I think. The (some?) initial buffer(s?) is still wrong, but after that we get input/rendering alignment.

I'm not sure if it's scaled correctly (it *seems* like maybe my test clients are double the size I'd expect, but that might be an artifact of my test environment).

**Comment by tarek-y-ismail** [comment]
> I'm not sure if it's scaled correctly (it _seems_ like maybe my test clients are double the size I'd expect, but that might be an artifact of my test environment).

You are correct. Should be fixed now

**Review by RAOF — CHANGES_REQUESTED** [review]
Right. That has fixed the first frame being wrong.

However, further testing has identified that the content of X11 windows isn't getting scaled at all. Setting the `x11-scale` option changes the size that Mir will configure the window to, but the content remains unscaled.

You should be able to test this locally, even without a HiDPI monitor, by setting `x11-scale=0.5`. This *should* result in the content of X11 windows being half-size; what currently happens is the window is configured to be half-size, but the content is rendered at 1.0 scale.

**Comment by Saviq** [comment]
> However, further testing has identified that the content of X11 windows isn't getting scaled at all. Setting the `x11-scale` option changes the size that Mir will configure the window to, but the content remains unscaled.
> 
> You should be able to test this locally, even without a HiDPI monitor, by setting `x11-scale=0.5`. This _should_ result in the content of X11 windows being half-size; what currently happens is the window is configured to be half-size, but the content is rendered at 1.0 scale.

Looks like you (too?) have `--x11-scale` in reverse:

> Our x11-scale option doesn't affect the client:
> ```
> $ miral-shell --help | grep --after 4 x11-scale
>   --x11-scale arg (=1.0)                The scale to assume X11 apps use. 
>                                         Defaults to the value of GDK_SCALE or 
>                                         1. Can be fractional. (Consider also 
>                                         setting GDK_SCALE in app-env-x11 when 
>                                         using this)
> ```

**Review by Saviq — APPROVED** [review]
Far I can tell, this looks good to me.

File: src/server/frontend_xwayland/xwayland_surface_role.cpp [hunk 2]
```diff
@@ -125,7 +119,13 @@ void mf::XWaylandSurfaceRole::commit(WlSurfaceState const& state)
         BOOST_THROW_EXCEPTION(std::runtime_error("Got XWaylandSurfaceRole::commit() when the role had no surface"));
     }
 
-    wl_surface->commit(state);
+    // HACK: Some applications might scale up while users don't want them to
+    // `--x11-scale` helps with this by scaling down the application according
+    // to user preference.
+    auto state_copy{state};
+    state_copy.scale = scale;
```
Comment (RAOF) [inline src/server/frontend_xwayland/xwayland_surface_role.cpp:126]: Oops! C++ will silently convert from `float` to `optional<int>`, meaning this only works for integer scale. (If you try `--x11-scale=0.5` Mir will immediately crash when the first X11 app starts, because this truncates `0.5f32` to `0i32`, and we later divide by `scale`)

**Review by RAOF — CHANGES_REQUESTED** [review]
This works for `--x11-scale=2.0`, but still isn't quite right. :thinking: 

I'll sync up with you this afternoon and see if we can't work out what right *is*!

**Review by RAOF — APPROVED** [review]
This now works.

I continue to suspect that this is fixing the problem by adding a new incorrect transformation that counteracts an existing incorrect transformation, but this generates the correct behaviour so is a strict improvement over the status-quo!

I think we need an overall review of WM coordinate handling, and that will be easier to act upon if the current state of the code generates the right behaviour!
