### PR TITLE
fix: move minimized windows to the back of the Z stack

### LINKED ISSUE #3904: Minimized windows should go to the back of the Z stack
> IMO minimized windows should go to the back (it is what happens on GNOME), so that when you Alt+Tab you get minimized windows at the end.

_Originally posted by @Saviq in https://github.com/canonical/mir/pull/3879#discussion_r2050740523_

### PR DESCRIPTION
**Pull request by panagiotisevaggelou**
This PR updates the behavior of MinimalWindowManager to ensure that minimized windows are sent to the back of the Z stack.

Changes
- Call send_tree_to_back() when a window is minimized.
- Updated affected tests to reflect the new stacking behavior.

Fixes #3904

### CODE REVIEW

**Review by AlanGriffiths — COMMENTED** [review]
I think the changed logic is expected to apply to all window management strategies, not just those derived from ``MinimalWindowManager`. That is it belongs in `BasicWindowManager::modify_window()` rather than `MinimalWindowManager::handle_modify_window()`

**Comment by panagiotisevaggelou** [comment]
@AlanGriffiths You are right, I've rebased the commit with the necessary changes. Thanks for pointing that out!

File: tests/window_management_tests/test_minimal_window_manager.cpp [hunk 1]
```diff
@@ -714,25 +714,25 @@ TEST_F(MinimalWindowManagerWithOneWindow, restoring_a_minimized_window_with_no_a
...
     request_modify(windows[1], spec);
 
     EXPECT_THAT(is_above(windows[2], windows[1]), Eq(true));
-    EXPECT_THAT(is_above(windows[1], windows[0]), Eq(true));
+    EXPECT_THAT(is_above(windows[0], windows[1]), Eq(true));
 }
 
 TEST_F(MinimalWindowManagerWithThreeWindows,
-    minimizing_the_active_window_selects_a_new_window_and_moves_the_minimized_down_in_the_z_order)
+    minimizing_the_active_window_selects_a_new_window_and_moves_it_to_the_back_of_the_z_order)
```
Comment (AlanGriffiths) [inline tests/window_management_tests/test_minimal_window_manager.cpp]: The referent of "it" is unclear

```suggestion
    minimizing_the_active_window_moves_it_to_the_back_of_the_z_order_and_selects_a_new_window)
```

**Comment by Saviq** [comment]
Kudos on #4000, too!

**Comment by Saviq** [comment]
@panagiotisevaggelou thanks again for your contributions!

If you find the time, could you please let us know what could've made your experience better?

We've a small form if that works for you: https://forms.gle/Vzgnk9L2HzhUeaM17, thanks!
