### PR TITLE
Make input_timestamp function unit testable

### LINKED ISSUE #4620: riscv64 builds are failing the `TimestampTest`
Looks like Copilot had a point here, riscv64 builds are failing:

```
148/240 Test #143: mir_unit_tests.TimestampTest.* ...................................................................***Failed   13.33 sec
Running main() from main.cpp
Note: Google Test filter = TimestampTest.*:-:--
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from TimestampTest
[ RUN ] TimestampTest.past_time_is_correctly_formatted
./tests/unit-tests/logging/test_input_timestamp.cpp:36: Failure
Value of: out
Expected: has substring "500.0"
Actual: "20106816477611 (500.481686ms ago)"

[ FAILED ] TimestampTest.past_time_is_correctly_formatted (19 ms)
[ RUN ] TimestampTest.future_time_is_correctly_formatted
./tests/unit-tests/logging/test_input_timestamp.cpp:48: Failure
Value of: out
Expected: has substring "1000.0"
Actual: "20108336922427 (999.936003ms in the future)"

[ FAILED ] TimestampTest.future_time_is_correctly_formatted (16 ms)
[----------] 2 tests from TimestampTest (37 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (40 ms total)
[ PASSED ] 0 tests.
[ FAILED ] 2 tests, listed below:
[ FAILED ] TimestampTest.past_time_is_correctly_formatted
[ FAILED ] TimestampTest.future_time_is_correctly_formatted

2 FAILED TESTS
```

_Originally posted by @Saviq in https://github.com/canonical/mir/pull/4593#pullrequestreview-3646555473_

### PR DESCRIPTION
**Pull request by DigraJatin**
Closes #4620

Related: Issue caused by below PR.
https://github.com/canonical/mir/pull/4593

## What's new?
Supply input_timestamp with a clock so that unit tests can use exact millisecond
values.

The tests previously expected fixed substrings such as "500.0" and
"1000.0", which can fail on slower or lower-resolution clocks (e.g.
riscv64) due to unavoidable scheduling and timing jitter.

## How to test
CI Server can test on PR actions.

### CODE REVIEW

**Comment by Saviq** [comment]
Thanks @DigraJatin, wonder if we could use [`ASSERT_NEAR`](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#floating-point-comparison) for this… though that would require parsing the number first…

**Comment by DigraJatin** [comment]
> Thanks @DigraJatin, wonder if we could use [`ASSERT_NEAR`](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#floating-point-comparison) for this… though that would require parsing the number first…

We can consider ASSERT_NEAR, but that would require parsing the formatted log string and choosing an arbitrary epsilon. Since this is a logging/formatting test (not a numeric API), I opted for regex-based range checks instead. This keeps the test focused on semantic correctness and avoids coupling to exact timing precision or formatting details.

**Comment by AlanGriffiths** [comment]
Is this solving the wrong problem?

I think the problem here is that the current signature of `input_timestamp()` is untestable as there's an implicit global `steady_clock::now()`.

A better design would be for the clock to be supplied: `input_timestamp(Clock const& clock, std::chrono::nanoseconds when)`. That would allow a mock time source to be supplied.

There are only a couple of call sites that would require fixup. (Note that the calls to `received_event_from_kernel()` typically need to convert from `std::chrono::*` to `int64_t` only for that to be converted to `std::chrono::nanoseconds` - that too could be cleaned up.)

**Comment by AlanGriffiths** [comment]
@copilot open a new pull request to apply changes based on the comments in [this thread](https://github.com/canonical/mir/pull/4621#pullrequestreview-3646722747)

**Comment by DigraJatin** [comment]
> @copilot open a new pull request to apply changes based on the comments in [this thread](https://github.com/canonical/mir/pull/4621#pullrequestreview-3646722747)

Is it okay if i take care of it today if a PR is already not ready ?
Just to confirm the changes we want to implment are to change the arguments of the orignal function - 
`input_timestamp(Clock const& clock, std::chrono::nanoseconds when)`
This also includes changing the references of this function throughout codebase.
Am i correct ?

**Comment by AlanGriffiths** [comment]
> Is it okay if i take care of it today

That's fine

File: include/common/mir/logging/input_timestamp.h [hunk 1]
```diff
@@ -19,13 +19,34 @@
...
+#include <cstdlib>
 
 namespace mir
 {
 namespace logging
 {
 
-std::string input_timestamp(std::chrono::nanoseconds when);
+template<typename Clock>
+std::string input_timestamp(Clock const& clock, std::chrono::nanoseconds when)
```
Comment (AlanGriffiths) [inline include/common/mir/logging/input_timestamp.h]: This doesn't need to be templated on Clock. Just use `mir::time::Clock`.

**Comment by DigraJatin** [comment]
Is there some issue with build checks ?
```
Run sudo --preserve-env apt-add-repository --yes ppa:mir-team/dev
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 452, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/apt-add-repository", line 435, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 89, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 133, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 111, in lp
    self._lp = login_func("%s.%s" % (self.__module__, self.__class__.__name__),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 494, in login_anonymously
    return cls(
           ^^^^
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 230, in __init__
    super(Launchpad, self).__init__(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 511, in __init__
    self._wadl = self._browser.get_wadl_application(self._root_uri)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 502, in get_wadl_application
    response, content = self._request(url, media_type=wadl_type)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 441, in _request
    response, content = self._request_and_retry(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 400, in _request_and_retry
    response, content = self._connection.request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1701, in request
    (response, content) = self._request(
                          ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 144, in _request
    response, content = super(LaunchpadOAuthAwareHttp, self)._request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 204, in _request
    return super(RestfulHttp, self)._request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1421, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1343, in _conn_request
    conn.connect()
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1179, in connect
    raise socket_err
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1133, in connect
    sock.connect((self.host, self.port))
OSError: [Errno 101] Network is unreachable
```

**Comment by tarek-y-ismail** [comment]
> Is there some issue with build checks ?

CI occasionally fails. Don't worry, your code is fine.

File: src/common/logging/input_timestamp.cpp [hunk 2]
```diff
@@ -19,10 +19,15 @@
...
 
 using namespace std::chrono;
-std::string mir::logging::input_timestamp(nanoseconds when)
+
+namespace mir
+{
+namespace logging
+{
+
+std::string input_timestamp(mir::time::Clock const& clock, std::chrono::nanoseconds when)
```
Comment (AlanGriffiths) [inline src/common/logging/input_timestamp.cpp]: We use the pre-existing style for a reason: it can only be interpreted as a definition, not a declaration.

```suggestion
std::string mir::logging::input_timestamp(mir::time::Clock const& clock, std::chrono::nanoseconds when)
```

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 3]
```diff
@@ -26,26 +27,42 @@ using namespace std::chrono_literals;
...
+    clock.current_time_value = steady_clock::time_point(1000ms);
+    auto const past_event = 250ms;
 
-    std::string out = ml::input_timestamp(past_event);
+    std::string out = ml::input_timestamp(clock, past_event);
 
-    EXPECT_THAT(out, Not(HasSubstr(".-")));
-    EXPECT_THAT(out, HasSubstr("500.0"));
+    EXPECT_THAT(out, HasSubstr("750"));
     EXPECT_THAT(out, HasSubstr("ms ago"));
```
Comment (AlanGriffiths) [inline tests/unit-tests/logging/test_input_timestamp.cpp]: We should be able to consolidate these tests

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 4]
```diff
@@ -26,26 +27,39 @@ using namespace std::chrono_literals;
...
+    clock.current_time_value = steady_clock::time_point(500ms);
+    auto const future_event = 750ms;
 
-    EXPECT_THAT(out, Not(HasSubstr(".-")));
-    EXPECT_THAT(out, HasSubstr("in the future"));
-    EXPECT_THAT(out, HasSubstr("1000.0"));
-    EXPECT_THAT(out, HasSubstr("ms"));
+    std::string out = ml::input_timestamp(clock, future_event);
 
+    EXPECT_THAT(out, AllOf(HasSubstr("250"), HasSubstr("ms"), HasSubstr("in the future")));
```
Comment (AlanGriffiths) [inline tests/unit-tests/logging/test_input_timestamp.cpp]:
```suggestion
    EXPECT_THAT(ml::input_timestamp(clock, future_event), AllOf(HasSubstr("250.000000ms in the future")));
```

File: tests/unit-tests/logging/test_input_timestamp.cpp [hunk 5]
```diff
@@ -26,26 +27,39 @@ using namespace std::chrono_literals;
...
+    clock.current_time_value = steady_clock::time_point(1000ms);
+    auto const past_event = 250ms;
 
-    std::string out = ml::input_timestamp(past_event);
+    std::string out = ml::input_timestamp(clock, past_event);
 
-    EXPECT_THAT(out, Not(HasSubstr(".-")));
-    EXPECT_THAT(out, HasSubstr("500.0"));
-    EXPECT_THAT(out, HasSubstr("ms ago"));
+    EXPECT_THAT(out, AllOf(HasSubstr("750"), HasSubstr("ms ago")));
```
Comment (AlanGriffiths) [inline tests/unit-tests/logging/test_input_timestamp.cpp]:
```suggestion
    EXPECT_THAT(ml::input_timestamp(clock, past_event), HasSubstr("750.000000ms ago"));
```

**Comment by DigraJatin** [comment]
Thanks @AlanGriffiths for adding a commit and merging this.

**Comment by tarek-y-ismail** [comment]
Thank **you** for the contribution!
